name: Ingestion Hebdomadaire Trains Européens

on:
  schedule:
    # Exécution tous les lundis à 4h00 UTC
    - cron: '0 4 * * 1'
  workflow_dispatch: # Permet de déclencher l'ingestion manuellement si besoin

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code du dépôt
      uses: actions/checkout@v4

    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'

    - name: Exécuter l'ingestion
      run: python ingest.py

    - name: Compresser la base SQLite
      run: gzip -f -9 eu_trains.db

    - name: Commit et Push
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f eu_trains.db.gz
        git commit -m "Auto-update: BDD SQLite compressée" || exit 0
        git push